/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import com.mysql.jdbc.Util;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
/**
 *
 * @author Muhammad Rizal
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Button_Optimasi = new javax.swing.JButton();
        Button_Ga = new javax.swing.JButton();
        Button_clear = new javax.swing.JButton();
        elitism = new javax.swing.JRadioButton();
        roullete = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();
        tesData = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tableBahan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        inputPopulasi = new javax.swing.JTextField();
        inputGenerasi = new javax.swing.JTextField();
        inputProbCross = new javax.swing.JTextField();
        inputProbMut = new javax.swing.JTextField();
        konsumsi = new javax.swing.JTextField();
        ayam = new javax.swing.JTextField();
        inputAlgoritma = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        Button_Pakan = new javax.swing.JButton();
        Button_Algo = new javax.swing.JButton();
        Button_Hasil = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 720));
        setSize(new java.awt.Dimension(1100, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Optimasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/simpan-awal.png"))); // NOI18N
        Button_Optimasi.setBorder(null);
        Button_Optimasi.setBorderPainted(false);
        Button_Optimasi.setContentAreaFilled(false);
        Button_Optimasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_Optimasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 90, 40));

        Button_Ga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/optimasi-awal.png"))); // NOI18N
        Button_Ga.setBorderPainted(false);
        Button_Ga.setContentAreaFilled(false);
        Button_Ga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_Ga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 90, 40));

        Button_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/trash-awal.png"))); // NOI18N
        Button_clear.setBorderPainted(false);
        Button_clear.setContentAreaFilled(false);
        Button_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 50, 40));

        buttonGroup1.add(elitism);
        elitism.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        elitism.setText("Elitism Selection");
        elitism.setContentAreaFilled(false);
        getContentPane().add(elitism, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        buttonGroup1.add(roullete);
        roullete.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        roullete.setText("Roullete Wheel");
        roullete.setContentAreaFilled(false);
        getContentPane().add(roullete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Metode Seleksi _.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, 20));
        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 690, 470));
        getContentPane().add(tesData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, -1, -1));

        scrollPane.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N

        tableBahan.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tableBahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kedelai", "3880", "38", "20", "2", "0.15", "0.37"},
                {"Bungkil Kelapa", "1525", "19.2", "2.1", "14.4", "0.17", "0.65"},
                {"Bungkil Kacang", "2205", "47", "1", "13", "0.2", "0.45"},
                {"Tepung ikan", "2580", "64.2", "5", "1", "3.73", "2.43"},
                {"Limbah udang", "1230", "45.2", "3,6", "15,9", "8.9", "1.9"}
            },
            new String [] {
                "Nama Bahan", "ME", "Protein", "Lemak", "Serat", "Kalsium", "Fosfor"
            }
        ));
        scrollPane.setViewportView(tableBahan);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 650, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/bahan-pakan2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 690, 470));

        inputPopulasi.setBorder(null);
        inputPopulasi.setOpaque(false);
        inputPopulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPopulasiActionPerformed(evt);
            }
        });
        inputPopulasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPopulasiKeyTyped(evt);
            }
        });
        getContentPane().add(inputPopulasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 20));

        inputGenerasi.setBorder(null);
        inputGenerasi.setOpaque(false);
        inputGenerasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputGenerasiKeyTyped(evt);
            }
        });
        getContentPane().add(inputGenerasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 100, 30));

        inputProbCross.setBorder(null);
        inputProbCross.setOpaque(false);
        inputProbCross.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputProbCrossKeyTyped(evt);
            }
        });
        getContentPane().add(inputProbCross, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 100, 30));

        inputProbMut.setBorder(null);
        inputProbMut.setOpaque(false);
        inputProbMut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputProbMutKeyTyped(evt);
            }
        });
        getContentPane().add(inputProbMut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 20));

        konsumsi.setBorder(null);
        konsumsi.setOpaque(false);
        konsumsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                konsumsiKeyTyped(evt);
            }
        });
        getContentPane().add(konsumsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 60, 30));

        ayam.setBorder(null);
        ayam.setOpaque(false);
        ayam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ayamKeyTyped(evt);
            }
        });
        getContentPane().add(ayam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 60, 30));

        inputAlgoritma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/parameter-input-1.png"))); // NOI18N
        getContentPane().add(inputAlgoritma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, 610));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        Button_Pakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/btn-feed.png"))); // NOI18N
        Button_Pakan.setBorderPainted(false);
        Button_Pakan.setContentAreaFilled(false);
        Button_Pakan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_Pakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, -1));

        Button_Algo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/btn-calculate.png"))); // NOI18N
        Button_Algo.setBorderPainted(false);
        Button_Algo.setContentAreaFilled(false);
        Button_Algo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_Algo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        Button_Hasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Button/btn-result.png"))); // NOI18N
        Button_Hasil.setBorderPainted(false);
        Button_Hasil.setContentAreaFilled(false);
        Button_Hasil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Button_Hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/bg-home.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JRadioButton getElitism(){
        return elitism;
    }
    
    public JRadioButton getRoullete(){
        return roullete;
    }

//button menu Optimasi=========================
//    public JScrollPane getScroll(){
//        return scrollPane;
//    }
//    
//    public JLabel getData(){
//        return tesData;
//    }
//    
//    public JTable getTable(){
//        return tableBahan;
//    }
    
//    Button clear =============
    public void ClearMouseListener(MouseListener l){
        this.Button_clear.addMouseListener(l);
    }
    
    public JButton getButton_Clear(){
        return Button_clear;
    }
    
    public void setButton_clear(JButton Button_clear){
        this.Button_clear = Button_clear;
    }
    
//    Button Otpimasi=============================
    public void RunMouseListener(MouseListener l){
        this.Button_Ga.addMouseListener(l);
    }
    
    public JButton getButton_Ga(){
        return Button_Ga;
    }
    
    public void setButton_Ga(JButton Button_Ga){
        this.Button_Ga = Button_Ga;
    }
    
//   Button Simpan ========================================
    public void OptimasiMouseListener(MouseListener l){
        this.Button_Optimasi.addMouseListener(l);
    }
    
    public JButton getButton_Optimasi() {
        return Button_Optimasi;
    }

    public void setButton_Optimasi(JButton Button_Optimasi) {
        this.Button_Optimasi = Button_Optimasi;
    }
    
    //button pakan============================
    public void PakanMouseListener(MouseListener l){
        this.Button_Pakan.addMouseListener(l);
    }
    
    public JButton getButton_Pakan() {
        return Button_Pakan;
    }

    public void setButton_pakan(JButton Button_Optimasi) {
        this.Button_Pakan = Button_Pakan;
    }
    
    //button algoritma=============================
    public void AlgoMouseListener(MouseListener l){
        this.Button_Algo.addMouseListener(l);
    }
    
    public JButton getButton_Algo() {
        return Button_Algo;
    }

    public void setButton_Algo(JButton Button_Optimasi) {
        this.Button_Algo = Button_Algo;
    }
    
    //Button hasil optimasi===========================
    public void HasilMouseListener(MouseListener l){
        this.Button_Hasil.addMouseListener(l);
    }
    
    public JButton getButton_Hasil() {
        return Button_Hasil;
    }

    public void setButton_Hasil(JButton Button_Optimasi) {
        this.Button_Hasil = Button_Hasil;
    }
    
    //set get panel
    
    public void setDynamicPanel(JPanel DynamicPanel) {
        this.DynamicPanel = DynamicPanel;
    }
    
    public JPanel getDynamicPanel(){
        return DynamicPanel;
    }
    
    public String getInputPopulasi(){
        return inputPopulasi.getText();
    }
    public JTextField getPopulasi(){
        return inputPopulasi;
    }
    
    public String getInputIterasi(){
        return inputGenerasi.getText();
    }
    public JTextField getIterasi(){
        return inputGenerasi;
    }
    
    public String getInputProbCross(){
        return inputProbCross.getText();
    }
    public JTextField getInputCross(){
        return inputProbCross;
    }
    
    public String getInputProbMut(){
        return inputProbMut.getText();
    }
    public JTextField getInputMut(){
        return inputProbMut;
    }
    
    public String getInputKonsumsi(){
        return konsumsi.getText();
    }
    public JTextField getKonsumsi(){
        return konsumsi;
    }
    
    public String getInputAyam(){
        return ayam.getText();
    }
    public JTextField getAyam(){
        return ayam;
    }
    
    private void inputPopulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPopulasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPopulasiActionPerformed

    private void inputPopulasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPopulasiKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_inputPopulasiKeyTyped

    private void inputGenerasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputGenerasiKeyTyped
       char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_inputGenerasiKeyTyped

    private void inputProbCrossKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputProbCrossKeyTyped
        char c = evt.getKeyChar();
        if (!((inputProbCross.getText()+evt.getKeyChar()).matches("[0-9]*(.[0-9]*)?"))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_inputProbCrossKeyTyped

    private void inputProbMutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputProbMutKeyTyped
       char c = evt.getKeyChar();
        if (!((inputProbMut.getText()+evt.getKeyChar()).matches("[0-9]*(.[0-9]*)?"))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_inputProbMutKeyTyped

    private void konsumsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_konsumsiKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_konsumsiKeyTyped

    private void ayamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ayamKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ayamKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Algo;
    private javax.swing.JButton Button_Ga;
    private javax.swing.JButton Button_Hasil;
    private javax.swing.JButton Button_Optimasi;
    private javax.swing.JButton Button_Pakan;
    private javax.swing.JButton Button_clear;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JTextField ayam;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton elitism;
    private javax.swing.JLabel header;
    private javax.swing.JLabel inputAlgoritma;
    private javax.swing.JTextField inputGenerasi;
    private javax.swing.JTextField inputPopulasi;
    private javax.swing.JTextField inputProbCross;
    private javax.swing.JTextField inputProbMut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField konsumsi;
    private javax.swing.JRadioButton roullete;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tableBahan;
    private javax.swing.JLabel tesData;
    // End of variables declaration//GEN-END:variables
}
